place/config/routes.rb
Rails.application.routes.draw do
  resources :holiday_types
  resources :holidays
  resources :authors
  resources :articles
  get 'welcome/index'


  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

place/app/controllers/holiday_types_controller.rb
class HolidayTypesController < ApplicationController
  before_action :set_holiday_type, only: [:show, :edit, :update, :destroy]

  # GET /holiday_types
  # GET /holiday_types.json
  def index
    @holiday_types = HolidayType.order(:name).all
  end

  # GET /holiday_types/1
  # GET /holiday_types/1.json
  def show
  end

  # GET /holiday_types/new
  def new
    @holiday_type = HolidayType.new
  end

  # GET /holiday_types/1/edit
  def edit
  end

  # POST /holiday_types
  # POST /holiday_types.json
  def create
    @holiday_type = HolidayType.new(holiday_type_params)

    respond_to do |format|
      if @holiday_type.save
        format.html { redirect_to @holiday_type, notice: 'Holiday type was successfully created.' }
        format.json { render :show, status: :created, location: @holiday_type }
      else
        format.html { render :new }
        format.json { render json: @holiday_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /holiday_types/1
  # PATCH/PUT /holiday_types/1.json
  def update
    respond_to do |format|
      if @holiday_type.update(holiday_type_params)
        format.html { redirect_to @holiday_type, notice: 'Holiday type was successfully updated.' }
        format.json { render :show, status: :ok, location: @holiday_type }
      else
        format.html { render :edit }
        format.json { render json: @holiday_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /holiday_types/1
  # DELETE /holiday_types/1.json
  def destroy
    @holiday_type.destroy
    respond_to do |format|
      format.html { redirect_to holiday_types_url, notice: 'Holiday type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_holiday_type
      @holiday_type = HolidayType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def holiday_type_params
      params.require(:holiday_type).permit(:name)
    end
end

place/app/helpers/holiday_types_helper.rb
module HolidayTypesHelper
end

place/app/views/holiday_types/_form.html.erb
<%= form_with(model: holiday_type, local: true) do |form| %>
  <% if holiday_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(holiday_type.errors.count, "error") %> prohibited this holiday_type from being saved:</h2>

      <ul>
        <% holiday_type.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

place/app/views/holiday_types/edit.html.erb
<h1>Editing Holiday Type</h1>

<%= render 'form', holiday_type: @holiday_type %>

<%= link_to 'Show', @holiday_type %> |
<%= link_to 'Back', holiday_types_path %>

place/app/views/holiday_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Holiday Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @holiday_types.each do |holiday_type| %>
      <tr>
        <td><%= holiday_type.name %></td>
        <td><%= link_to 'Show', holiday_type %></td>
        <td><%= link_to 'Edit', edit_holiday_type_path(holiday_type) %></td>
        <td><%= link_to 'Destroy', holiday_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Holiday Type', new_holiday_type_path %>

place/app/views/holiday_types/new.html.erb
<h1>New Holiday Type</h1>

<%= render 'form', holiday_type: @holiday_type %>

<%= link_to 'Back', holiday_types_path %>

place/app/views/holiday_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @holiday_type.name %>
</p>

<%= link_to 'Edit', edit_holiday_type_path(@holiday_type) %> |
<%= link_to 'Back', holiday_types_path %>