place/config/routes.rb
Rails.application.routes.draw do
  resources :holiday_types
  resources :holidays
  resources :authors
  resources :articles
  get 'welcome/index'


  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

place/app/models/holiday.rb
class Holiday < ApplicationRecord
  enum country: ['AU','CA','US']
  has_and_belongs_to_many :holiday_types

end

place/app/models/holiday_type.rb
class HolidayType < ApplicationRecord
  has_and_belongs_to_many :holiday
end

place/app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController
  before_action :set_holiday, only: [:show, :edit, :update, :destroy]

  # GET /holidays
  # GET /holidays.json
  def index
    @holidays = Holiday.all
  end

  # GET /holidays/1
  # GET /holidays/1.json
  def show
  end

  # GET /holidays/new
  def new
    @holiday = Holiday.new
  end

  # GET /holidays/1/edit
  def edit
  end

  # POST /holidays
  # POST /holidays.json
  def create
    @holiday = Holiday.new(holiday_params)

    respond_to do |format|
      if @holiday.save
        format.html { redirect_to @holiday, notice: 'Holiday was successfully created.' }
        format.json { render :show, status: :created, location: @holiday }
      else
        format.html { render :new }
        format.json { render json: @holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /holidays/1
  # PATCH/PUT /holidays/1.json
  def update
    respond_to do |format|
      if @holiday.update(holiday_params)
        format.html { redirect_to @holiday, notice: 'Holiday was successfully updated.' }
        format.json { render :show, status: :ok, location: @holiday }
      else
        format.html { render :edit }
        format.json { render json: @holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /holidays/1
  # DELETE /holidays/1.json
  def destroy
    @holiday.destroy
    respond_to do |format|
      format.html { redirect_to holidays_url, notice: 'Holiday was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_holiday
      @holiday = Holiday.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def holiday_params
      params.require(:holiday).permit(:name, :description, :country, :holiday_date, :states)
    end
end

place/app/helpers/holidays_helper.rb
module HolidaysHelper
end

place/app/views/holidays/_form.html.erb
<%= form_with(model: holiday, local: true) do |form| %>
  <% if holiday.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(holiday.errors.count, "error") %> prohibited this holiday from being saved:</h2>

      <ul>
        <% holiday.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.number_field :country %>
  </div>

  <div class="field">
    <%= form.label :holiday_date %>
    <%= form.date_select :holiday_date %>
  </div>

  <div class="field">
    <%= form.label :states %>
    <%= form.text_field :states %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

place/app/views/holidays/edit.html.erb
<h1>Editing Holiday</h1>

<%= render 'form', holiday: @holiday %>

<%= link_to 'Show', @holiday %> |
<%= link_to 'Back', holidays_path %>

place/app/views/holidays/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Holidays</h1>

<table>
  <thead>
    <tr>
      <th class="holiday_date">Holiday date</th>
      <th>Name</th>
      <th class="description">Description</th>
      <th class="centered">Country</th>
      <th class="centered">States</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @holidays.each do |holiday| %>
      <tr>
        <td><%= holiday.holiday_date %></td>
        <td><%= holiday.name %></td>
        <td><%= holiday.description %></td>
        <td class="centered"><%= holiday.country %></td>
        <td class="centered"><%= holiday.states.gsub(',',', ') %></td>
        <td><%= link_to 'Show', holiday %></td>
        <td><%= link_to 'Edit', edit_holiday_path(holiday) %></td>
        <td><%= link_to 'Destroy', holiday, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Holiday', new_holiday_path %>

place/app/views/holidays/new.html.erb
<h1>New Holiday</h1>

<%= render 'form', holiday: @holiday %>

<%= link_to 'Back', holidays_path %>

place/app/views/holidays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @holiday.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @holiday.description %>
</p>

<p>
  <strong>Country:</strong>
  <%= @holiday.country %>
</p>

<p>
  <strong>Holiday date:</strong>
  <%= @holiday.holiday_date %>
</p>

<p>
  <strong>States:</strong>
  <%= @holiday.states %>
</p>

<%= link_to 'Edit', edit_holiday_path(@holiday) %> |
<%= link_to 'Back', holidays_path %>